# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 211182498073964615284c79ab203931837762e9108944a2c6b8ddf0ad7c7a1e1dc7588303dff0ba940f6bad61d20b77d3d0721299edc454c2c8d27efa701cf2

test:
  secret_key_base: af8ac3e17e0634600cb10f87d270e12526e2f20b037248080f715376de726d7f0c2fc042dea13d949cf758480f0fde52014cd8b3c38ab308240c8a0861222709

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
